third_party/memfault/wscript
I ended up setting this in `src/fw/wscript` instead, so remove the dead
code.
See reference here:
https://github.com/coredevices/pebbleos/pull/3#discussion_r2154194597
Signed-off-by: Noah Pendleton <noah@memfault.com>
=> fw/memfault: clean up old comment about LTO

src/fw/services/normal/data_logging/data_logging_service.h, third_party/memfault/port/src/memfault_chunk_collector.c, third_party/memfault/port/src/memfault_chunk_collector.h, third_party/memfault/port/src/memfault_platform_port.c
In normal FW only, collect chunks from Memfault every 15
minutes and forward them to the mobile app using datalogging.
Mobile implementation to read/upload these is already done.
Signed-off-by: Steve Penna <steve@penna.org.uk>
=> fw/memfault: Push memfault chunks to datalogging

src/fw/drivers/wscript_build
Added the GPIO driver in #78, but it's still the wrong path in wscript_build, now fix it
=> fw/drivers/sf32lb52: Fix gpio driver path

src/fw/debug/debug.c
The reason was always returned as 0 because debug_reboot_reason_print resets it.
Tested: we now see real reboot reasons in the memfault portal.
=> fw: Init Memfault before reboot reason is reset

src/fw/drivers/pmic/npm1300.c
In the Asterix bootloader, we carefully set voltages to make sure that any ADC errors in nPM1300 do not mess up a running system.  Well, nPM1300 erratum 27 says that if we set the voltage to a voltage that is already set, then we get an extra 1 mA of quiescent current!  And indeed we do.  We work around this by turning the voltage up by 100 mV, and then back down again.  This is equivalent to if we had not ever tripped the erratum to begin with (I tested this by modifying the bootloader not to trip the erratum and measuring power).
Saves ~800 uA in OS sleep (on top of all other changes), saves ~780 uA in `wfi forever` floor state (floor current now 778 uA with this and all other changes).
=> drivers/pmic/npm1300: workaround nPM1300 erratum 27

src/fw/board/board_nrf5.h, src/fw/board/boards/board_asterix.h, src/fw/drivers/display/sharp_ls013b7dh01/sharp_ls013b7dh01_nrf5.c, src/fw/drivers/task_watchdog.c
This PR reverts #98, it looks like the VCOM toggle signal is no longer generated correctly.
TP30 before revert:
After revert:
FYI @jwise
=> Revert PR #98

src/bluetooth-fw/nimble/bas.c, src/bluetooth-fw/nimble/init.c, src/bluetooth-fw/qemu/bas.c, src/bluetooth-fw/stub/bas.c, src/fw/services/common/bluetooth/ble_bas.c, src/fw/services/common/bluetooth/ble_bas.h, src/fw/services/common/bluetooth/bluetooth_ctl.c, src/include/bluetooth/bas.h, third_party/nimble/port/include/cc2564x/syscfg/syscfg.h, third_party/nimble/port/include/nrf52/syscfg/syscfg.h, third_party/nimble/port/include/sf32lb52/syscfg/syscfg.h, third_party/nimble/syscfg/app/pkg.yml, third_party/nimble/wscript
This can be used by the mobile app to show watch battery % in the device list or do whatever the app wants with this.
=> Expose standard BLE BAS service

src/fw/applib/applib_malloc.json, src/fw/applib/graphics/gtypes.c, src/fw/applib/graphics/gtypes.h, src/fw/applib/ui/kino/kino_layer.c, src/fw/applib/ui/kino/kino_layer.h, src/fw/applib/ui/kino/kino_player.c, src/fw/applib/ui/kino/kino_player.h, src/fw/apps/system_apps/settings/settings_notifications.c, src/fw/apps/system_apps/timeline/peek_layer.c, src/fw/apps/system_apps/timeline/peek_layer.h, src/fw/popups/notifications/notification_window.c, src/fw/services/normal/notifications/alerts_preferences.c, src/fw/services/normal/notifications/alerts_preferences_private.h, src/fw/services/normal/timeline/layout_layer.c, src/fw/services/normal/timeline/notification_layout.c, src/fw/services/normal/timeline/swap_layer.c
This pull request introduces a new alternative notification style on black and white watches that can be changed to in settings ("old" design is still default)
https://github.com/user-attachments/assets/c5f4daf3-a10d-46ab-9a91-3579a1afe633
https://github.com/user-attachments/assets/3d2ee553-f1a3-413d-90b5-e76a4d2aaf2f
=> feat: add alternative notification design option and related preferences

src/fw/board/board_sf32lb52.h, src/fw/board/boards/board_obelix.c, src/fw/drivers/sf32lb52/button.c, src/fw/drivers/sf32lb52/debounced_button.c, src/fw/drivers/sf32lb52/debounced_button_definitions.h, src/fw/drivers/sf32lb52/gpio.c, src/fw/drivers/wscript_build
This add button and debounced_button driver for obelix board.
EDIT: 
~Below log show timer and gpio read is OK. Next step to check the exti function.~
Currently add button support for Sifli SF32LB52-DevKit-LCD board. Will add obelix new board support latter.
=> obelix add button driver

src/fw/drivers/mic/nrf5/pdm.c, src/fw/drivers/mic/nrf5/pdm_definitions.h
The nRF52 microphone driver was causing out-of-memory crashes due to large static buffer allocations (~1920 bytes) that were allocated permanently even when the microphone wasn't in use.
Changes:
- Convert static PDM and circular buffers to dynamically allocated pointers
- Add prv_allocate_buffers() and prv_free_buffers() functions
- Allocate buffers only when mic_start() is called
- Free buffers when mic_stop() is called or on initialization failure
- Add safety checks to prevent operations on unallocated buffers
=> fw/drivers/mic: Convert nRF52 PDM driver to dynamic memory allocation

sdk/tools/pebble_package.py, sdk/waftools/pebble_sdk_lib.py
This fixes building Pebble Packages under Python 3. Before this, using existing Pebble Packages inside a project worked fine, but creators of Pebble Packages couldn't build their packages.
=> Fix building Pebble Packages

src/fw/drivers/imu/lsm6dso/lsm6dso.c
The main contribution of this patchset is to avoid vibing causing spurious events to be fired.
Otherwise, there are a few cleanups to aid future developers grokking the code.
=> LSM6DSO: Avoid spurious events due to vibing

third_party/memfault/wscript
If needed in other builds, one can always set `--memfault=1` when configuring.
=> third_party/memfault: enable by default only on release mode

.gitmodules
Upstream contains again all we need.
=> third_party/hal_sifli: switch to upstream

src/fw/console/dbgserial_input.c, src/fw/console/dbgserial_input.h, src/fw/drivers/nrf5/uart.c, src/fw/kernel/util/stop.c, wscript
We can, in fact, have our cake and eat it too.  No need to choose between power consumption and debugging!
=> kernel/stop: turn off dbgserial UART during stop on power-hungry platforms

.github/workflows/build-firmware.yml, .github/workflows/build-prf.yml, .github/workflows/release.yml
It sure would be nice to be able to console into a Pebble running a production firmware and see what's going on in there.
=> ci: store loghash_dict as artifacts

src/fw/applib/health_service.c, src/fw/apps/system_apps/health/health.c, src/fw/apps/system_apps/workout/workout.c, src/fw/services/normal/activity/activity.c, src/fw/services/normal/activity/activity.h, src/fw/services/normal/activity/insights_settings.c, src/fw/services/normal/services_normal.c, src/fw/shell/normal/system_app_registry_list.json
Fixes https://github.com/coredevices/PebbleOS/issues/188 / FIRM-497
In order to fix the issue, we only initialize the activity service once the rtc is past 2010-01-01 (since Pebble was released in 2013 and I don't believe in time travel!)
I've added early returns to quite a bit of activity.c in order to allow pebble os to boot. (i have probably added a bit too many but better safe than sorry :P).
I've also added checks to health and workout so that they arent launchable until we have init'd.
The health service from applib provides dummy data until activity is initialized, so that stuff like kickstart (which I have added to asterix in this pr also) works :)
=> Fix for RTC reset causing step count to reset [FIRM-497]

src/fw/applib/health_service.c, src/fw/services/normal/activity/activity.c, src/fw/syscall/syscall.h
activity_is_initialized() reads the kernel-privileged symbol s_activity_initialized (located in kernel BSS). 
If an Applib/user task directly reads this kernel variable, the MPU detects the operation as an invalid access to protected memory. The result: hardfault.
To circumvent this, activity_is_initialized is now implemented as a syscall for applib
=> fw/applib/health_service: update init check to use syscall [FIRM-535]

src/fw/drivers/imu/lsm6dso/lsm6dso.c
This reverts commit ebfe8a45c7895017c84183635111777194de662e.
Accelerometer appears to be too sensitive, causing lots of watch wakeups/light ON events.
=> Revert "drivers/imu/lsm6dso: Improve shake sensitivity"

tools/readcore.py
This was an extremely enjoyable afternoon and evening of hacking.  Tested against the core dump in MOB-1513, and it does seem to get a reasonable looking stack trace in each thread, though the ISR thread looks suspicious (whether it is suspicious because of the core dump tool or something else, different question...).
=> tools/readcore: add "readcore" tool to convert Pebble core dumps to ELF [FIRM-543]

resources/normal/base/tzdata/timezones_olson.txt, tools/timezones.py
Fixes FIRM-566
Updated the timezone database (`timezones_olson.txt`) by running 
update_timezones.py.
(Compilation failed until I also added `Eire` to the `dstzone` list).
Tested that the watch showed the wrong time for Mexico City before this 
change (off by one hour), then the correct time after flashing this 
change.
Signed-off-by: Steve Penna <steve@penna.org.uk>
=> resources/normal/base/tzdata: Update timezone database

src/fw/drivers/sf32lb52/jdi_lpm015m135a.c
Resolve jdi_lpm015m135a the display abnormalities in the first and last columns of the screen.
Signed-off-by: Jerrywang <[w200024212@163.com](mailto:w200024212@163.com)>
=> fw/drivers/sf32lb52/jdi_lpm015m135a:  Optimize jdi display para

src/fw/applib/ui/dialogs/actionable_dialog.c, src/fw/applib/ui/dialogs/actionable_dialog.h, src/fw/applib/ui/dialogs/actionable_dialog_private.h, src/fw/apps/system_apps/settings/settings_system.c, src/fw/debug/debug_reboot_reason.c, src/fw/kernel/event_loop.c, src/fw/popups/crashed_ui.c, src/fw/popups/crashed_ui.h, src/fw/shell/normal/prefs.c, src/fw/shell/normal/prefs_values.h.inc, src/fw/shell/prefs.h, src/fw/shell/prf/stubs.c
As per FIRM-615, we surface two options to create a core dump: an immediate core dump option (previously hidden behind Settings -> System -> Information -> long-press Firmware), and a "core dump any time" option that can be enabled to trigger a core dump by rapidly clicking the back button 10 times in a row (intended for use with debugging FIRM-425).
We also create a 'debugging' menu in system settings (gated behind a confirmation dialog) to control these, and, while we're at it, if the user voluntarily creates a core dump, then we pop up a special dialog on reboot to explain why there was an unceremonious reboot, and to tell the user to go and upload the crash dump through CoreApp.
=> FIRM-615: create on-device debugging options to generate a core dump

src/fw/drivers/imu/lsm6dso/lsm6dso.c
This patch enhances the LSM6DSO driver’s interrupt watchdog recovery sequence to prevent repeated lockups and ensure new interrupts fire after recovery
=> fw/drivers/imu/lsm6dso: enhance interrupt watchdog callback for improved sensor recovery

src/fw/drivers/imu/lsm6dso/lsm6dso.c
This pull request improves the robustness of the LSM6DSO IMU driver by enhancing its interrupt handling and recovery logic. It adds a multi-stage recovery mechanism for sensor recovery when interrupts are missed, escalating from simple recovery attempts to full reinitialization if necessary. This should help the system recover gracefully from sensor lockups and improve reliability.
Introduced a multi-stage watchdog recovery system. After a configurable number of simple recovery attempts (`LSM6DSO_SIMPLE_WATCHDOG_RECOVERY_ATTEMPTS`), the system escalates to a forced sensor reinitialization via the new `prv_lsm6dso_force_reinit()` function.
* Added the `s_watchdog_recovery_attempts` counter to track recovery attempts and control escalation.
* Improved logging for watchdog events, recovery …
=> drivers/imu/lsm6dso: enhance interrupt watchdog with recovery attempts and forced reinitialization

src/fw/wscript
As of now, on platforms where e.g. PRF can be XIP from a random address (not necessarily the origin of flash, nor first slot), crashed could happen due to `memory_layout_is_pointer_in_region()` returning invalid responses (`__FLASH_size__` would be wrong).
Things are still messy, but this at least now report the true flash start/size on platforms like Obelix.
Fixes FIRM-635
=> fw/wscript: fix/improve linker script flash handling

src/fw/drivers/imu/lsm6dso/lsm6dso.c
With core56 we finally achieved that the accel *really really* automatically recovers
The problem is though that there was a gap of a few minutes where the accel locks up and we dont recover!
So now, we force reinit every time, shorten the watchdog to 30 seconds and also quiet down logs since until now we would have every single watchdog run even if we dont try to recover anything!
=> lsm6dso: tighten watchdog, simplify recovery, and quiet down logs

tools/analyze_coredump.py, tools/gdb_scripts/gdb_heap.py, tools/gdb_scripts/gdb_parser.py, tools/gdb_scripts/gdb_tintin.py, tools/gdb_scripts/gdb_tintin_metadata.py
`gdb_tintin` had a handful of Python2-isms; it *almost* worked but did not quite.  It turns out that these GDB scripts are quite useful, though, and it would be nice to have them! `pbl lockstats` is particularly nice for hunting down deadlocks when analyzing a core dump.
=> tools/gdb_scripts: bring gdb_tintin into the modern era

src/fw/apps/system_apps/settings/settings_display.c
Fixes "Backlight" toggle hiding itself in display settings
When toggling the "Backlight" option off in the display settings screen it would disappear, preventing the user from turning the backlight back on
Changed the number of backlight sub items count to only take into account the sub items and not the main backlight setting too
=> fw/apps/system_apps/settings_display: fix backlight self-hiding

src/fw/apps/system_apps/settings/settings_display.c
Actually fixes "Backlight" toggle hiding itself in display settings from #329 
With all the git actions I missed the -1 that actually fixes the problem and just added the clip
When toggling the "Backlight" option off in the display settings screen it would disappear, preventing the user from turning the backlight back on
Changed the number of backlight sub items count to only take into account the sub items and not the main backlight setting too
=> fw/apps/settings_display: actually fix backlight option

src/fw/drivers/imu/lsm6dso/lsm6dso.c
Two small fixes for the LSM6DSO driver's watchdog logic:
The watchdog was force re-initing every 10 seconds, even when samples are not actively being requested!
The watchdog timer wasn't being removed before `prv_lsm6dso_force_reinit()` reset state and called `prv_lsm6dso_chase_target_state()`. Since `chase_target_state()` adds the timer when transitioning `s_lsm6dso_running` from false→true, this created duplicate timers or confused the timer system.
This explains field reports where the sensor took 15-30 seconds of shaking to recover, and log messages showing "no interrupts for 12922 ms" when the watchdog should fire every 10 seconds. The timer just... wasn't firing on schedule. Now it will actually run every 10 seconds like it's supposed to.
=> Misc LSM6DSO accelerometer fixes

third_party/memfault/wscript
The MEMFAULT preprocessor define was moved to the build function in b7a08564, which meant it was only set in the local memfault build context and not propagated to firmware sources. This caused all `#if MEMFAULT` checks in src/fw/ to evaluate as undefined/false, breaking memfault metrics collection for release builds.
Move the define back to configure() so it's set globally for all build targets, while keeping the Obelix PRF library build disabled.
=> third_party/memfault: fix MEMFAULT define not being set globally
