src/fw/drivers/sf32lb52/temperature.c
src/fw/drivers/wscript_build

fw/drivers/sf32lb52: Add temperature sensor driver

---

src/fw/drivers/sf32lb52/gpio.c

fw/drivers/sf32lb52: Add gpio drivers

---

third_party/nimble/transport/hci_sf32lb52.c

Reduce copy of HCI data.
Fixes https://github.com/coredevices/PebbleOS/issues/62

Update HCI driver for SF32LB52X

---

src/fw/board/boards/board_asterix.h
src/fw/drivers/nrf5/rtc.c

Add core16a sleep mode change, update battery estimate to 130h.
Will merge by hand after CI runs.

asterix: battery improvements

---

docs/getting_started.md

this was a blocker when I was helping them get it installed

docs: add openocd dependency and change cd pebbles

---

src/fw/drivers/sf32lb52/qspi.c
third_party/hal_sifli/sf32lb52/lcpu_config.c
third_party/hal_sifli/wscript
third_party/nimble/transport/hci_sf32lb52.c

Alternative to https://github.com/coredevices/PebbleOS/pull/112

Some fixes for Obelix

---

.gitmodules
src/fw/services/normal/voice/voice.c
src/fw/services/normal/voice/voice_speex.c
src/fw/services/normal/voice/voice_speex.h
src/fw/services/wscript
src/fw/wscript
third_party/speex/config.h
third_party/speex/os_support_custom.h
third_party/speex/speex_config_types.h
third_party/speex/wscript
third_party/wscript

note that this will overflow flash on asterix without an option such as --nojs

fw: Add Speex audio codec support

---

src/fw/board/board_sf32lb52.h
src/fw/board/boards/board_obelix.c
src/fw/board/boards/board_obelix.h
src/fw/drivers/imu/imu_obelix.c
src/fw/drivers/wscript_build
third_party/wscript

Enable LSM6DSO accelerometer on Obelix

---

src/fw/drivers/imu/lsm6dso/lsm6dso.c

Users have reported that the accelerometer randomly stops working, with symptoms including:
- Shake to backlight stops functioning
- Step counting ceases
- Motion-based watch face features break
- Issue persists until device reboot
- Affects multiple users intermittently
The LSM6DSO driver lacked robust error handling for I2C communication failures:
1. **No I2C error detection**: Failed reads/writes were ignored, leaving the driver unaware of communication issues
2. **Missing health monitoring**: No mechanism to detect when the sensor becomes unresponsive
3. **No recovery logic**: Once communication failed, the driver had no way to recover without full system restart
4. **Silent failures**: Errors weren't tracked or logged adequately for debugging
This PR implements comprehensive error …

fw/drivers/lsm6dso: Add error detection and recovery

---

src/fw/drivers/imu/lsm6dso/lsm6dso.c

In my testing it now pretty much matches silk :D

drivers/imu/lsm6dso: Improve shake sensitivity

---

src/fw/services/normal/notifications/ancs/ancs_notifications.c

Calendar events with alarms fire twice - once correctly before the event, and again after the event saying "X min ago". This happens because:
We send a notification for the event
iOS also sends ANCS notifications for the same events
The ANCS filtering only checked if any reminders exist, not for specific matches
Solution:
Enhanced the calendar ANCS filtering to check for exact matches (timestamp + title) in the reminder database.
Note: I was unable to test this directly due to not having an iOS device

fw/services/notifications: Enhance calendar reminder filtering logic [FIRM-480]

---

.github/workflows/build-firmware.yml
.github/workflows/build-prf.yml
.github/workflows/build-qemu.yml
.github/workflows/release.yml

Apparently we're getting hit by npm rate limit, let's see if this helps.

ci: cache npm dependencies

---

src/fw/drivers/sf32lb52/debounced_button.c
src/fw/drivers/sf32lb52/exti.c
src/fw/drivers/sf32lb52/jdi_lpm015m135a.c
src/fw/drivers/sf32lb52/uart.c

This try to fix the race condition for sf32lb52 jdi driver. Fix: #178

[DNM] fw/jdi: fix sf32lb52 display write race conditon

---

waftools/nrfutil.py
wscript

This can be useful when using JLink-based tooling (which I use all the time).

Add support for nrfutil

---

src/fw/services/common/accel_manager.c

It looks like the Pebble accel manager came with a race that could occur when start/stopping activity tracking (this happens e.g. when plugging the charger).
The problem could occur if prv_call_data_callback() was called for a state assigned to KernelBackground task (which defers to system task queue), then data from a previous event was consumed (so clearing the event posted flag) and then activity was stopped. Because flag was cleared despite having a new event in the queue, the unsubscribe/delete logic did not defer the de-allocation properly, causing a use-after-free when the actuall callback was processed.
The current code is still incorrect, if >1 event is queued, free will still occur (as sys_accel_manager_data_unsubscribe effectively booleanizes the new events posted counter). I …

fw/services/common/accel_manager: fix use-after-free

---

src/fw/drivers/sf32lb52/qspi.c

This allows the operating system to schedule other tasks during the intervals between erasing or writing multiple regions, thereby avoiding prolonged blocking.

fw/drivers/sf32lb52/qspi: Shrink flash op critical section

---

platform/platform_capabilities.py
src/fw/board/board_sf32lb52.h
src/fw/board/boards/board_obelix.c
src/fw/board/boards/board_obelix.h
src/fw/drivers/mic/sf32lb52/pdm.c
src/fw/drivers/mic/sf32lb52/pdm_definitions.h
src/fw/drivers/pmic/npm1300.c
src/fw/drivers/wscript_build

Add PDM dirver for SF32LB52

---

src/fw/drivers/vibe/vibe_aw86225.c

fw/drivers/vibe: enhance vibe strength for aw86225

---

src/fw/board/boards/board_obelix.c
src/fw/drivers/led_controller.h

changes default backlight color

---

src/fw/apps/prf_apps/mfg_backlight_app.c
src/fw/apps/prf_apps/mfg_backlight_app.h
src/fw/apps/prf_apps/mfg_menu_app.c

fw/apps/prf: add backlight mfg testing app

---

src/fw/services/common/accel_manager.c
src/fw/util/shared_circular_buffer.c
src/fw/util/shared_circular_buffer.h

Fix integer overflow in accel manager

---

third_party/nimble/port/include/sf32lb52/syscfg/syscfg.h
third_party/nimble/syscfg/targets/sf32lb52/syscfg.yml

third_party/nimble: increase ACL pool for SF32LB52

---

src/fw/drivers/sf32lb52/debounced_button.c

SF32LB52 GPTIM2 clock frequency is 24MHz.
fix: #301

fw/debounced_button: fix sf32lb52 incorrect clock

---

src/fw/drivers/sf32lb52/jdi_lpm015m135a.c

This PR is focusing on obelix display performance.
Progress:
1.  the button timer same as pwm led, which cause button event more slow, or gui response more slow.
-- fix: use the gptim2 for button instead
The `display_update` spend nearly 37 ms. `222_TO_332` convert about 3~4ms.
The display_update call stack as below.
```
-> HAL_LCDC_SendLayerData2Reg_IT
-> SendLayerData_IT
-> _SendLayerData
-> LayerUpdate
-> wait HAL_LCDC_SendLayerDataCpltCbk.
```

fw/display: Improve obelix display performance 

---

src/fw/apps/system_apps/settings/settings_display.c
src/fw/services/common/compositor/compositor.c
src/fw/shell/normal/prefs.c
src/fw/shell/normal/prefs_values.h.inc
src/fw/shell/prefs.h

I really wanted this feature to make Obelix my daily driver, so I coded something quick. It's ok in most cases; some watch faces scale better than the others (we use nearest-neighbor scaling).

Add support for scaling legacy apps

---

src/fw/apps/prf_apps/mfg_audio_app.c
src/fw/apps/prf_apps/mfg_audio_app.h
src/fw/apps/prf_apps/mfg_menu_app.c
src/fw/board/board_sf32lb52.h
src/fw/board/boards/board_obelix.c
src/fw/board/boards/board_obelix.h
src/fw/drivers/audio.h
src/fw/drivers/sf32lb52/audio/audec.c
src/fw/drivers/sf32lb52/audio/audio.c
src/fw/drivers/sf32lb52/audio/audio_definitions.h
src/fw/drivers/sf32lb52/audio/sf32lb_audio.h
src/fw/drivers/wscript_build
src/fw/wscript

Implementation for sf32lb52 audio decoder dirver on obelix platform
Fixes #35

sf32lb52 audio decoder driver 

---

src/fw/popups/notifications/notification_window.c

We had a User that had blank screens appear when notifications failed to load. This PR makes that blank screen not appear.
(This doesnt fix the underlying issue the user was having, but they cannot reproduce it anymore and there haven't been any other reports. If there is an issue, users will probably file it as "notifications not appearing" now instead of "blank notification")

fw/popups/notifications: avoid blank SwapLayer on load failure [FIRM-516]

---

src/fw/services/normal/process_management/app_order_storage.c

Trying to open a missing file can be slower than expected if the file system has _many files, as it needs to read the file name on each start page, compare, etc. It turns out this can introduce noticeable delays in the app_order_storage path (e.g., from watchface to menu) because app_order_read_order() will be called repeatedly in app_menu_data_source:prv_sorted_add because it always returns NULL, causing an unnecessary amount of file system lookups. To just try once until the file is created, cache its existence.

fw/services/normal/process_management/app_order_storage: cache missing file state

---

src/fw/services/common/hrm/hrm_manager.c

This PR fixes the "Dropping X Accel Samples" spam issue in the HRM manager.
The HRM manager was not consuming all prepared accelerometer samples when the buffer was full. This caused the accelerometer manager to repeatedly warn about dropped samples, even though the issue was in the consumption logic rather than actual data loss.
Introduced a separate `num_samples_to_copy` variable to track how many samples can actually be stored in the buffer, while ensuring that `sys_accel_manager_consume_samples()` is always called with the full `num_new_samples` count. This ensures all prepared samples are properly consumed from the accelerometer manager, preventing spurious warning messages.

fw/services/hrm_manager: ensure all samples are consumed

---

src/fw/apps/system_apps/toggle/backlight_state.c
src/fw/apps/system_apps/toggle/backlight_state.h
src/fw/shell/normal/system_app_registry_list.json

Added a new option to quick toggles section for turning the backlight on and off :D

feat: add backlight toggle quick setting
